### ISSUE TITLE
compilation error (make menuconfig)

### ISSUE THREAD

**Issue by scuty2000** [paldier/d7000v2#1]
when running "make menuconfig" on my ubuntu 18.x machine I get this error:

Argument "4.2.1" isn't numeric in numeric ge (>=) at /home/luca/Scrivania/d7000v2/scripts/feeds line 25.
Use of uninitialized value $line[1] in pattern match (m//) at /home/luca/Scrivania/d7000v2/scripts/feeds line 55, <FEEDS> line 1.
Use of uninitialized value $line[2] in split at /home/luca/Scrivania/d7000v2/scripts/feeds line 56, <FEEDS> line 1.
Syntax error in feeds.conf, line: 1
Argument "4.2.1" isn't numeric in numeric ge (>=) at /home/luca/Scrivania/d7000v2/scripts/feeds line 25.
Use of uninitialized value $line[1] in pattern match (m//) at /home/luca/Scrivania/d7000v2/scripts/feeds line 55, <FEEDS> line 1.
Use of uninitialized value $line[2] in split at /home/luca/Scrivania/d7000v2/scripts/feeds line 56, <FEEDS> line 1.
Syntax error in feeds.conf, line: 1
Collecting package info: done
Argument "4.2.1" isn't numeric in numeric ge (>=) at /home/luca/Scrivania/d7000v2/scripts/feeds line 25.
Use of uninitialized value $line[1] in pattern match (m//) at /home/luca/Scrivania/d7000v2/scripts/feeds line 55, <FEEDS> line 1.
Use of uninitialized value $line[2] in split at /home/luca/Scrivania/d7000v2/scripts/feeds line 56, <FEEDS> line 1.
Syntax error in feeds.conf, line: 1
Collecting target info: done
Argument "4.2.1" isn't numeric in numeric ge (>=) at ./scripts/feeds line 25.
Use of uninitialized value $line[1] in pattern match (m//) at ./scripts/feeds line 55, <FEEDS> line 1.
Use of uninitialized value $line[2] in split at ./scripts/feeds line 56, <FEEDS> line 1.
Syntax error in feeds.conf, line: 1
make: *** [/home/luca/Scrivania/d7000v2/include/toplevel.mk:75: prepare-tmpinfo] Error 25

EDIT:

also occurring on Ubuntu 14.04 x64

**Comment by paldier** [comment]
Argument "4.2.1" isn't numeric in numeric ge (>=) at ./scripts/feeds line 25.
do you understand?
